version: '3.8'

services:
  currency-server:
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: currency-server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/api/exchange-rates"]
      interval: 30s
      timeout: 10s
      retries: 3